
CREATE DATABASE DUMACODES;
USE   DUMACODES;

CREATE TABLE PERFIL
(
	 CH_ID_PERFIL CHAR(8) PRIMARY KEY NOT NULL,
     VC_NOMBRE VARCHAR(30)
);

CREATE TABLE DOCUMENTO_IDENTIDAD
(
	CH_ID_DOCUMENTO CHAR(8) PRIMARY KEY NOT NULL,
	VC_NOMBRE_DOCUMENTO VARCHAR(30)
);

CREATE TABLE USUARIO
(
	CH_ID_USUARIO CHAR(30) PRIMARY KEY NOT NULL UNIQUE,
    VC_PASSWORD VARCHAR(30),
    CH_ID_PERFIL CHAR(8),
    VC_NOMBRE VARCHAR(50),
    VC_APELLIDO_PATERNO VARCHAR(50),
    VC_APELLIDO_MATERNO VARCHAR(50),
    CH_ID_DOCUMENTO CHAR(8),
    CH_NUMERO_DOCUMENTO CHAR(8),
    VC_ESTADO VARCHAR(30) DEFAULT 'HABILITADO',
    VC_EMAIL VARCHAR(50),
	VC_EMPRESA VARCHAR(50),
    DT_FECHA_CREACION DATETIME,
    CH_ID_USUARIO_CREACION CHAR(8)
);

ALTER TABLE USUARIO ADD CONSTRAINT FK_PERFIL  FOREIGN KEY (CH_ID_PERFIL) 
REFERENCES PERFIL(CH_ID_PERFIL);
ALTER TABLE USUARIO ADD CONSTRAINT FK_NUMERO_DOC FOREIGN KEY(CH_ID_DOCUMENTO) 
REFERENCES DOCUMENTO_IDENTIDAD(CH_ID_DOCUMENTO);


CREATE  TABLE DISENO (
VC_COBERTURA VARCHAR(50),
VC_CODIGO VARCHAR(50),
VC_IIBB VARCHAR(100),
VC_CODIGO_IIBB VARCHAR(50),
NU_LATITUD_A DECIMAL(9,6),
NU_LONGITUD_A DECIMAL(9,6),
NU_LATITUD_B DECIMAL(9,6),
NU_LONGITUD_B DECIMAL(9,6)
);


CREATE TABLE EQUIPAMIENTOAIO(
VC_SOLUCION VARCHAR(30),
VC_REGION VARCHAR(30),
DT_F_ENTREGA DATETIME,
VC_CODIGO_KIT VARCHAR(30),
VC_SERIE_KIT VARCHAR(30),
VC_CODIGO_GILAT VARCHAR(30),
VC_DESCRIPCION VARCHAR(100),
IN_CANTIDAD INTEGER,
VC_NUM_SERIE VARCHAR(30),
VC_SERIE_CORTA VARCHAR (30)
);

CREATE TABLE NODO (
CH_CODIGO_NODO CHAR(7) PRIMARY KEY NOT NULL,
VC_PROYECTO VARCHAR(30),
VC_NOMBRE VARCHAR(50),
VC_DEPARTAMENTO VARCHAR(30),
VC_PROVINCIA VARCHAR(50),
VC_DISTRITO VARCHAR(50),
VC_LOCALIDAD VARCHAR(50),
VC_UBIGEO VARCHAR(30),
NU_LATITUD NUMERIC(10,7),
NU_LONGITUD NUMERIC(10,7),
IN_ANILLO INTEGER,
IN_ALTURA_TORRE INTEGER,
DT_FECHA_CREACION DATETIME,
CH_ID_USUARIO CHAR(8)
);

CREATE TABLE TAREA (
  CH_ID_LINK  char(7) DEFAULT NULL,
  CH_ISO_NODO  char(11) DEFAULT NULL,
  VC_TIP_LINK  varchar(30) DEFAULT NULL,
  VC_CONTRATISTA varchar(8) DEFAULT NULL,
  DT_INICIO_INST  datetime DEFAULT NULL,
  DT_FIN_INST  datetime DEFAULT NULL,
  VC_PROYECTO  varchar(30) DEFAULT NULL,
  VC_TIP_NODO_A  varchar(30) DEFAULT NULL,
  VC_ID_NODO_A  varchar(30) DEFAULT NULL,
  VC_TIP_NODO_B  varchar(30) DEFAULT NULL,
  VC_ID_NODO_B  varchar(30) DEFAULT NULL,
  VC_SECTOR_AP  varchar(30) DEFAULT NULL,
  DT_FECHA_CREACION  datetime DEFAULT NULL,
  CH_ID_USUARIO_CREACION  char(8) DEFAULT NULL
) ;

CREATE TABLE PMP(
VC_CODIGO_SITE_A VARCHAR(30)  NOT NULL,
IN_SECTOR_AP INT,
VC_IIBB_SITE_B VARCHAR(50),
VC_CODIGO_IIBB_SITE_B VARCHAR(30),
NU_LATITUD_B NUMERIC(7,5),
NU_LONGITUD_B NUMERIC(7,5),
VC_ODU_MODEL_A VARCHAR(30),
VC_ODU_MODEL_B VARCHAR(30),
VC_ANTENA_MODEL_A VARCHAR(30),	
VC_ANTENA_MODEL_B VARCHAR(30),
NU_ANTENA_GAIN_A NUMERIC(3,1),
NU_ANTENA_GAIN_B NUMERIC(3,1),
NU_ANTENA_HEIGHT_A NUMERIC(3,1),
NU_AZIMUTH_A NUMERIC(5,2),
NU_AZIMUTH_B NUMERIC(5,2),
NU_ELEVATION_A NUMERIC(3.1),
NU_ELEVATION_B NUMERIC(3,1),
NU_TXPOWER_A NUMERIC(3,1),
NU_TXPOWER_B NUMERIC(3,1),
NU_EIRP_A NUMERIC(3,1),
NU_EIRP_B NUMERIC(3,1),
NU_THRESHOLD_A NUMERIC(3,1),
NU_THRESHOLD_B NUMERIC(3,1),
NU_RX_LEVEL_A NUMERIC(3,1),
NU_RX_LEVEL_B NUMERIC(3,1),
NU_FADE_MARGIN_A NUMERIC(3,1),
NU_FADE_MARGIN_B NUMERIC(3,1),
VC_LINK_CONFIG VARCHAR(50),
IN_CENTRAL_FRECUENCY INT,
IN_CHANNEL INT,
VC_MODULATION VARCHAR(30),
NU_AVAILABILITY NUMERIC(7,4),
NU_DISTANCE_KM NUMERIC(5,3),
DT_FECHA_CREACION DATETIME,
CH_ID_USUARIO_CREACION CHAR(8)
);


CREATE TABLE  IP_PLANNING_PMP(
VC_ESTACION_A VARCHAR(30),
VC_IP_A VARCHAR(30),
VC_ESTACION_B VARCHAR(30),
VC_IP_B VARCHAR(30),
VC_MASCARA_A_B VARCHAR(30),
VC_DEFAULT_A_B VARCHAR(30),
VC_IP_LOCAL VARCHAR(30),
VC_PUERTO_A VARCHAR(30),
VC_PUERTO_B VARCHAR(30),
DT_FECHA_CREACION DATETIME,
CH_ID_USUARIO_CREACION CHAR(8)
);
