<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ptpModel extends Model
{
    protected $table = 'PTP';
    public $timestamps = false;
    public $incrementing = false;

    protected $fillable = [
        'CH_ID_NODO_S1','CH_ID_NODO_S2','NU_AZIMUTH_S1','NU_AZIMUTH_S2','NU_ELEVACION_S1',
        'NU_ELEVACION_S2','NU_DISTANCIA_KM','NU_COTA_MSNM_S1','NU_COTA_MSNM_S2','VC_ANTENA_MODEL_S1',
        'VC_ANTENA_MODEL_S2','VC_DIAMETRO_ANTENA_S1','VC_DIAMETRO_ANTENA_S2','IN_ALTURA_ANTENA_S1',
        'IN_ALTURA_ANTENA_S2','NU_GANANCIA_ANTENA_S1','NU_GANANCIA_ANTENA_S2','CH_CHANEL_S1',
        'CH_CHANEL_S2','VC_DISEÑO_FRECUENCIA_S1','VC_DISEÑO_FRECUENCIA_S2','VC_POLARIZACION','VC_RADIO_MODEL_S1',
        'VC_EMISSION_S1','IN_TX_POWER_S1','IN_TX_POWER_S2','NU_EIRP_S1','NU_EIRP_S2','NU_RX_THRESHOLD_S1',
        'NU_RECEIVE_SIGNAL_S1','NU_RECEIVE_SIGNAL_S2','NU_FADE_MARGIN_S1','NU_FADE_MAGIN_S2','NU_ANNUAL_MULTIPATH_AVAILABILITY_S1',
        'NU_ANNUAL_RAIN_AVAILABILITY_S1','NU_ANNUAL_RAIN_AND_MULTIPATH_AVAILABILITY','DT_FECHA_CREACION',
        'CH_ID_USUARIO_CREACION'
    ];
}
